baseURL = "https://33nano.netlify.app/"
languageCode = "en-us"
title = "Prince Namwali"
theme = "dream"

# copyright = ""

# googleAnalytics = ""

# disqusShortname = ""

# enableRobotsTXT = true

[params]
  background = "#f7f7f7"
  # backgroundImage = "/me/background.jpg"
  linkColor = "seagreen"

  # dark mode
   defaultDark = true
   backgroundDark = "black"
  # backgroundImageDark = "/me/background-dark.jpg"
  # darkLinkColor = "darkseagreen"
  # darkNav = true
  # dark404 = true

  author = "Prince Namwali"
  # description = ""
  avatar = "/img/main.png"
   headerTitle = "Prince Namwali"
  motto = "Lifelong Learner, Digital Nomad & Game Dev"
  # categoriesLimitInHeader = 6 # deprecated
  # headerBottomText = "" # deprecated

  # footerBottomText = ""

  # rss = true

  # utterancesRepo = ""

  # valine = true
  # LEANCLOUD_APP_ID = ""
  # LEANCLOUD_APP_KEY = ""

   twitter = "https://twitter.com/Anno_denomini"
   linkedin = "https://www.linkedin.com/in/33nano/"
   github = "https://github.com/33nano"
   stackoverflow = "https://stackoverflow.com/users/story/13772339"

  siteStartYear = 2021

  # favicon = "/favicon.ico"

  # highlightjs = true
  # highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
  # highlightjsExtraLanguages = ["ocaml"]
  # highlightjsTheme = "gruvbox-light"
  # highlightjsThemeDark = "gruvbox-dark"

  # search
  # enableSearch = true

  # options
  # showSummaryCoverInPost = true
  # hasTwitterEmbed = true

  # [params.advanced]
  #   customCSS = ["css/custom.css"]
  #   customJS = []
