baseURL = "https://33nano.xyz/"
languageCode = "en-us"
title = "Prince Namwali"
theme = "dream"

googleAnalytics = "UA-162757063-2"

[params]
  background = "#f7f7f7"
  # backgroundImage = "/me/background.jpg"
  linkColor = "seagreen"

  # dark mode
   defaultDark = true
   backgroundDark = "black"
  # backgroundImageDark = "/me/background-dark.jpg"
  # darkLinkColor = "darkseagreen"
  # darkNav = true
  # dark404 = true

  author = "Prince Namwali"
  # description = ""
  avatar = "/img/main.png"
   headerTitle = "🇵 🇰 🇳"
  motto = "Dreams don't come true, decisions do."
  # categoriesLimitInHeader = 6 # deprecated
  # headerBottomText = "" # deprecated

  # footerBottomText = ""

  # rss = true

  # utterancesRepo = ""

  # valine = true
  # LEANCLOUD_APP_ID = ""
  # LEANCLOUD_APP_KEY = ""

  
   
  # github = "33nano"
  # gamejolt = "@Drqueef"
  # LBRY  =
  # Discord =
  # Itch =
  # Anilist =
  # Gamejolt =

  siteStartYear = 2021

   favicon = "/favicon.ico"

  # highlightjs = true
  # highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
  # highlightjsExtraLanguages = ["ocaml"]
  # highlightjsTheme = "gruvbox-light"
  # highlightjsThemeDark = "gruvbox-dark"

  # search
   enableSearch = true
   
[outputs]
  home = ["HTML", "RSS", "JSON"]
  
  # options
  # showSummaryCoverInPost = true
  # hasTwitterEmbed = true

   [params.advanced]
     customCSS = ["css/custom.css"]
  #   customJS = []
